/**
 * "Powered by Intel / AMD / Windows — Make in India".
 *
 * The supplied artwork is drawn for a light background: its "Powered by", the
 * AMD wordmark and the Make in India lion are black, so on this site's near
 * black page they disappear. It was previously sat on a white plate to cope,
 * which turned into a black slab on the light theme (index.css inverts
 * bg-white under html.light) and a white slab on the dark one. Either way a
 * rectangle floating on the page.
 *
 * So there is a reversed copy, and no plate at all. It is generated by flipping
 * ONLY the neutral ink -- the pixels with no saturation, which is the black and
 * grey lettering and the lion. Intel's blue, Microsoft's blue and AMD's green
 * arrow are left exactly as supplied, because those colours are part of those
 * marks. That is what a reversed lockup is, and it is why the strip can sit
 * directly on either background without a box around it.
 *
 * These are third-party trademarks and the reversed copy is DERIVED, not
 * official. Intel, AMD and Microsoft all publish reversed assets in their
 * partner kits; dropping those in over
 * public/images/Group-29-reversed.png is the right thing to do before launch.
 */
export const PartnerStrip = ({ className = "h-6 md:h-7 w-auto", testid }) => (
  <span className="inline-flex items-center" data-testid={testid}>
    <img
      src="/images/Group-29.png"
      alt="Powered by Intel, AMD, Windows — Make in India"
      loading="lazy"
      className={`${className} themed-ink`}
      data-testid={testid ? `${testid}-light` : undefined}
    />
    <img
      src="/images/Group-29-reversed.png"
      alt="Powered by Intel, AMD, Windows — Make in India"
      aria-hidden="true"
      loading="lazy"
      className={`${className} themed-reversed`}
      data-testid={testid ? `${testid}-reversed` : undefined}
    />
  </span>
);
